version: '3.8'

services:
  elasticsearch:
    build:
      context: ../../../
      dockerfile: resources/docker/files/develop/elasticsearch/Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
        #- ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
        #- ./resources/elasticsearch/sudachi.json:/usr/share/elasticsearch/config/sudachi/sudachi.json # ← ここを修正
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  eval-manage:
    build:
      context: ../../../tools/eval_manage/
      dockerfile: resources/docker/files/develop/Dockerfile
    container_name: eval-manage
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    networks:
      - elastic
    volumes:
      - ../../../tools/eval_manage/:/app/

networks:
  elastic:
    driver: bridge

volumes:
  esdata:
    driver: local
