up:
	docker-compose -f resources/docker/compose/docker-compose.yml up --build
up-eval:
	docker-compose -f resources/docker/compose/docker-compose.yml up eval-manage --build
exec-es:
	docker-compose -f resources/docker/compose/docker-compose.yml exec elasticsearch bash
